import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { PageWrapper } from '../../components/layout/PageWrapper'
import { getStudent } from '../../services/student.service'

interface Student {
  id: string
  first_name: string
  last_name: string
  middle_name: string | null
  reg_number: string
  gender: string | null
  date_of_birth: string | null
  address: string | null
  photo_url: string | null
  guardian_name: string | null
  guardian_phone: string | null
  guardian_email: string | null
  parent_linking_code: string
  profile_completed: boolean
  is_active: boolean
  created_at: string
  classes: { level: string; arm: string } | null
}

export const StudentDetail = () => {
  const { id } = useParams()
  const navigate = useNavigate()
  const [student, setStudent] = useState<Student | null>(null)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    const load = async () => {
      if (!id) return
      setIsLoading(true)
      try {
        const data = await getStudent(id)
        setStudent(data)
      } catch {
        setError('Failed to load student')
      } finally {
        setIsLoading(false)
      }
    }
    load()
  }, [id])

  const handlePrintLoginSlip = () => {
    if (!student) return
    const pin = student.reg_number.slice(-4)
    const printContent = `
      <html>
        <head>
          <title>Login Slip - ${student.first_name} ${student.last_name}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; max-width: 400px; margin: 0 auto; }
            h2 { color: #1d4ed8; margin-bottom: 4px; }
            .school { color: #6b7280; font-size: 14px; margin-bottom: 24px; }
            .label { font-size: 12px; color: #6b7280; margin-top: 16px; }
            .value { font-size: 18px; font-weight: bold; color: #111827; letter-spacing: 2px; }
            .divider { border: none; border-top: 1px dashed #e5e7eb; margin: 24px 0; }
            .footer { font-size: 11px; color: #9ca3af; margin-top: 24px; }
            .warning { background: #fef3c7; border: 1px solid #fcd34d; padding: 12px; border-radius: 8px; font-size: 12px; color: #92400e; margin-top: 16px; }
          </style>
        </head>
        <body>
          <h2>SchoolPilot</h2>
          <p class="school">Student Login Slip</p>
          <hr class="divider" />
          <p class="label">Student Name</p>
          <p class="value" style="font-size:16px; letter-spacing:0">${student.last_name} ${student.first_name} ${student.middle_name ?? ''}</p>
          <p class="label">Class</p>
          <p class="value" style="font-size:16px; letter-spacing:0">${student.classes ? `${student.classes.level} ${student.classes.arm}` : '—'}</p>
          <hr class="divider" />
          <p class="label">Reg Number (Username)</p>
          <p class="value">${student.reg_number}</p>
          <p class="label">Default PIN</p>
          <p class="value">${pin}</p>
          <p class="label">Parent Linking Code</p>
          <p class="value">${student.parent_linking_code}</p>
          <hr class="divider" />
          <div class="warning">
            ⚠️ Keep this slip safe. Change your PIN on first login at your school portal.
          </div>
          <p class="footer">Generated by SchoolPilot · schoolpilot.ng</p>
        </body>
      </html>
    `
    const win = window.open('', '_blank')
    if (win) {
      win.document.write(printContent)
      win.document.close()
      win.print()
    }
  }

  if (isLoading) {
    return (
      <PageWrapper title="Student Detail">
        <div className="flex items-center justify-center h-64">
          <div className="h-8 w-8 animate-spin rounded-full border-4 border-blue-600 border-t-transparent" />
        </div>
      </PageWrapper>
    )
  }

  if (error || !student) {
    return (
      <PageWrapper title="Student Detail">
        <div className="text-center py-12">
          <span className="text-5xl">😕</span>
          <p className="text-gray-500 mt-4">{error || 'Student not found'}</p>
          <button
            onClick={() => navigate('/students')}
            className="mt-4 px-4 py-2 bg-blue-600 text-white rounded-xl text-sm font-medium"
          >
            Back to Students
          </button>
        </div>
      </PageWrapper>
    )
  }

  return (
    <PageWrapper title="Student Detail">
      <div className="max-w-3xl">

        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <button
            onClick={() => navigate('/students')}
            className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-200 transition-colors"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
            Student Profile
          </h2>
        </div>

        {/* Profile Card */}
        <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-6 mb-4">
          <div className="flex items-start gap-5">

            {/* Photo */}
            <div className="w-20 h-20 rounded-2xl bg-blue-50 dark:bg-blue-900/30 overflow-hidden shrink-0 flex items-center justify-center">
              {student.photo_url ? (
                <img
                  src={student.photo_url}
                  alt={student.first_name}
                  className="w-full h-full object-cover"
                />
              ) : (
                <span className="text-3xl font-bold text-blue-600 dark:text-blue-400">
                  {student.first_name[0]}{student.last_name[0]}
                </span>
              )}
            </div>

            {/* Info */}
            <div className="flex-1">
              <div className="flex items-center gap-2 flex-wrap">
                <h3 className="text-xl font-bold text-gray-900 dark:text-white">
                  {student.last_name} {student.first_name} {student.middle_name ?? ''}
                </h3>
                {!student.profile_completed && (
                  <span className="px-2 py-0.5 bg-yellow-100 text-yellow-700 text-xs font-semibold rounded-full">
                    Profile Incomplete
                  </span>
                )}
                {!student.is_active && (
                  <span className="px-2 py-0.5 bg-red-100 text-red-600 text-xs font-semibold rounded-full">
                    Inactive
                  </span>
                )}
              </div>
              <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">
                {student.classes ? `${student.classes.level} ${student.classes.arm}` : 'No class assigned'}
              </p>
              <p className="text-gray-400 text-xs mt-0.5">
                Enrolled {new Date(student.created_at).toLocaleDateString('en-NG', {
                  day: 'numeric', month: 'long', year: 'numeric'
                })}
              </p>
            </div>

            {/* Print Login Slip */}
            <button
              onClick={handlePrintLoginSlip}
              className="inline-flex items-center gap-2 px-4 py-2 border border-gray-200 dark:border-gray-700 text-gray-600 dark:text-gray-400 text-sm font-medium rounded-xl hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors shrink-0"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
              </svg>
              Print Login Slip
            </button>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">

          {/* Login Credentials */}
          <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5">
            <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">
              Login Credentials
            </h4>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-gray-400">Reg Number</p>
                <p className="text-sm font-bold text-gray-900 dark:text-white tracking-wider">
                  {student.reg_number}
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-400">Default PIN</p>
                <p className="text-sm font-bold text-gray-900 dark:text-white tracking-wider">
                  {student.reg_number.slice(-4)}
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-400">Parent Linking Code</p>
                <p className="text-sm font-bold text-blue-600 dark:text-blue-400 tracking-wider">
                  {student.parent_linking_code}
                </p>
              </div>
            </div>
          </div>

          {/* Personal Info */}
          <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5">
            <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">
              Personal Information
            </h4>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-gray-400">Gender</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white capitalize">
                  {student.gender ?? '—'}
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-400">Date of Birth</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {student.date_of_birth
                    ? new Date(student.date_of_birth).toLocaleDateString('en-NG', {
                        day: 'numeric', month: 'long', year: 'numeric'
                      })
                    : '—'}
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-400">Address</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {student.address ?? '—'}
                </p>
              </div>
            </div>
          </div>

          {/* Guardian Info */}
          <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5">
            <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">
              Guardian Information
            </h4>
            <div className="space-y-3">
              <div>
                <p className="text-xs text-gray-400">Guardian Name</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {student.guardian_name ?? '—'}
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-400">Guardian Phone</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {student.guardian_phone ?? '—'}
                </p>
              </div>
              <div>
                <p className="text-xs text-gray-400">Guardian Email</p>
                <p className="text-sm font-medium text-gray-900 dark:text-white">
                  {student.guardian_email ?? '—'}
                </p>
              </div>
            </div>
          </div>

          {/* Profile Status */}
          <div className="bg-white dark:bg-gray-900 rounded-2xl border border-gray-100 dark:border-gray-800 p-5">
            <h4 className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-4">
              Profile Completion
            </h4>
            <div className="space-y-2">
              {[
                { label: 'Basic Info', done: true },
                { label: 'Class Assigned', done: !!student.classes },
                { label: 'Photo Uploaded', done: !!student.photo_url },
                { label: 'Date of Birth', done: !!student.date_of_birth },
                { label: 'Address', done: !!student.address },
                { label: 'Guardian Info', done: !!student.guardian_name },
              ].map((item) => (
                <div key={item.label} className="flex items-center gap-2">
                  <div className={`w-4 h-4 rounded-full flex items-center justify-center ${
                    item.done ? 'bg-green-100' : 'bg-gray-100 dark:bg-gray-800'
                  }`}>
                    {item.done ? (
                      <svg className="w-2.5 h-2.5 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                      </svg>
                    ) : (
                      <div className="w-1.5 h-1.5 rounded-full bg-gray-300 dark:bg-gray-600" />
                    )}
                  </div>
                  <p className={`text-sm ${item.done ? 'text-gray-900 dark:text-white' : 'text-gray-400'}`}>
                    {item.label}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </PageWrapper>
  )
}